#!/bin/bash
#PBS -N install_python_lib
#PBS -l nodes=1:ppn=1
#PBS -l walltime=00:10:00
#PBS -j oe
#PBS -q gpu_v100_q

cd $PBS_O_WORKDIR

# Activate the virtual environment (if applicable)
source myenv/bin/activate

# Install the Python library
pip install library_name

# Deactivate the virtual environment (if applicable)
deactivate
